"""added age table

Revision ID: b0c09ca18a9b
Revises: 4711f6d94931
Create Date: 2026-08-21 15:08:33.834024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c09ca18a9b'
down_revision: Union[str, Sequence[str], None] = '4711f6d94931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persons', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'age')
    # ### end Alembic commands ###
